before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd/pull-watch
    binary: pull-watch
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

# .goreleaser.yaml
brews:
  - name: pull-watch
    homepage: "https://github.com/ship-digital/pull-watch"
    description: "A tool that watches a git repository for changes and runs a specified command"
    license: "MIT"
    repository:
      owner: ship-digital
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    install: |
      bin.install "pull-watch"
    icon: "https://raw.githubusercontent.com/ship-digital/pull-watch/main/assets/pull-watch-icon.svg"

upx:
  - enabled: true
    compress: "best"
    lzma: true
    brute: true

    # Only compress Linux and Windows builds
    goos: [linux, windows]
    goarch: [amd64, arm64]

chocolateys:
  - name: pull-watch
    title: "Pull Watch"
    authors: Ship Digital
    project_url: "https://github.com/ship-digital/pull-watch"
    license_url: "https://github.com/ship-digital/pull-watch/blob/main/LICENSE"
    require_license_acceptance: false
    project_source_url: "https://github.com/ship-digital/pull-watch"
    docs_url: "https://github.com/ship-digital/pull-watch/blob/main/README.md"
    bug_tracker_url: "https://github.com/ship-digital/pull-watch/issues"
    tags: "git pull watch monitor automation"
    summary: "A tool that watches a git repository for changes and runs a specified command"
    description: |
      Pull Watch is a tool that monitors git repositories for changes and
      automatically executes specified commands when updates are detected.
    release_notes: "https://github.com/ship-digital/pull-watch/releases/tag/v{{.Version}}"
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false
    icon_url: "https://raw.githubusercontent.com/ship-digital/pull-watch/main/assets/pull-watch-icon.png"