before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd/pull-watch
    binary: pull-watch
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

# .goreleaser.yaml
brews:
  - name: pull-watch
    homepage: "https://github.com/ship-digital/pull-watch"
    description: "A tool that watches a git repository for changes and runs a specified command"
    license: "MIT"
    repository:
      owner: ship-digital
      name: homebrew-tap
    directory: Formula
    install: |
      bin.install "pull-watch"

upx:
  - enabled: true
    compress: "best"
    lzma: true
    brute: true

    # Only compress Linux and Windows builds
    goos: [linux, windows]
    goarch: [amd64, arm64]