name: release-please

on:
  push:
    branches:
      - main
  # Allow manual trigger for testing winget updates after a release exists
  workflow_dispatch:
    inputs:
      target_tag:
        description: "Manually specify the tag name (e.g., v1.7.0) to run post-release jobs (npm, winget) for testing/reruns. Leave empty on normal main push."
        required: false
        default: ""

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: go

  # New job to centralize tag determination and run condition
  determine-release-info:
    needs: release-please
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
      tag_name: ${{ steps.check.outputs.tag_name }}
      tag_name_no_v: ${{ steps.check.outputs.tag_name_no_v }}
    steps:
      - name: Check conditions and determine tag
        id: check
        run: |
          SHOULD_RUN="false"
          TARGET_TAG=""
          TAG_NAME_NO_V=""

          # Check if release-please created a release OR if manually triggered with a tag
          if [[ "${{ needs.release-please.outputs.release_created }}" == "true" && -n "${{ needs.release-please.outputs.tag_name }}" ]]; then
            echo "Condition met: Release created by release-please."
            SHOULD_RUN="true"
            TARGET_TAG="${{ needs.release-please.outputs.tag_name }}"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.target_tag }}" ]]; then
            echo "Condition met: Manual workflow dispatch with target tag."
            SHOULD_RUN="true"
            TARGET_TAG="${{ github.event.inputs.target_tag }}"
          else
            echo "Condition not met. No release created and not a manual run with a tag."
          fi

          if [[ "$SHOULD_RUN" == "true" ]]; then
            echo "Determined Target Tag: ${TARGET_TAG}"
            TAG_NAME_NO_V="${TARGET_TAG#v}"
            echo "Determined Target Tag (no v): ${TAG_NAME_NO_V}"
          fi

          echo "should_run=${SHOULD_RUN}" >> $GITHUB_OUTPUT
          echo "tag_name=${TARGET_TAG}" >> $GITHUB_OUTPUT
          echo "tag_name_no_v=${TAG_NAME_NO_V}" >> $GITHUB_OUTPUT

  # This job runs GoReleaser *only* if the condition in determine-release-info is met
  goreleaser:
    needs: determine-release-info # Depends on the new job
    if: ${{ needs.determine-release-info.outputs.should_run == 'true' }} # Use the output from the new job
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # GoReleaser needs the full history
          fetch-tags: true # Fetch tags too

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Set up UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Install Chocolatey
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2
          workdir: .
          # GoReleaser automatically uses the checked-out tag when run in this context
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
          WINGET_GITHUB_TOKEN: ${{ secrets.WINGET_GITHUB_TOKEN }}

      - name: Upload GoReleaser artifacts
        uses: actions/upload-artifact@v4
        with:
          # Use the tag name from the determine-release-info job output
          name: goreleaser-artifacts-${{ needs.determine-release-info.outputs.tag_name }}
          path: dist/

  publish-npm:
    needs: [goreleaser, determine-release-info] # Depends on the new job
    if: ${{ needs.determine-release-info.outputs.should_run == 'true' }} # Use the output from the new job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download GoReleaser artifacts
        uses: actions/download-artifact@v4
        with:
          # Use the tag name from the determine-release-info job output
          name: goreleaser-artifacts-${{ needs.determine-release-info.outputs.tag_name }}
          path: dist/

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Update package.json version
        # Use the tag name (no v) from the determine-release-info job output
        run: npm version --no-git-tag-version ${{ needs.determine-release-info.outputs.tag_name_no_v }}

      - name: Install Node.js dependencies for publish script
        run: npm install

      - name: Publish to npm using custom script
        run: node scripts/publish-npm.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: "true"
          # Use the tag name from the determine-release-info job output
          RELEASE_TAG: ${{ needs.determine-release-info.outputs.tag_name }}

  update-winget-pr:
    name: Update Winget PR Manifest
    needs: [goreleaser, determine-release-info] # Depends on the new job
    if: ${{ needs.determine-release-info.outputs.should_run == 'true' }} # Use the output from the new job
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Removed the redundant 'Get Target Tag Name' step

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Checkout Main Repo for Templates
        uses: actions/checkout@v4
        with:
          path: main-repo

      # This step assumes GoReleaser (run in the 'goreleaser' job) has already pushed
      # the initial manifests and created the branch in the winget fork.
      - name: Wait for Winget Manifests from GoReleaser
        id: wait_for_manifests
        env:
          # Use outputs from determine-release-info
          TARGET_TAG: ${{ needs.determine-release-info.outputs.tag_name }}
          APP_VERSION_NO_V: ${{ needs.determine-release-info.outputs.tag_name_no_v }}
          WINGET_PUBLISHER: ShipDigital
          WINGET_PACKAGE: PullWatch
          WINGET_REPO_OWNER: ship-digital
          WINGET_REPO_NAME: winget-pkgs
        run: |
          #!/bin/bash
          set -eo pipefail
          retries=5
          delay=15
          branch_name="pull-watch-${TARGET_TAG}"
          manifest_path="manifests/s/${WINGET_PUBLISHER}/${WINGET_PACKAGE}/${APP_VERSION_NO_V}/${WINGET_PUBLISHER}.${WINGET_PACKAGE}.installer.yaml"
          repo_url="https://github.com/${WINGET_REPO_OWNER}/${WINGET_REPO_NAME}.git"

          echo "Attempting to clone winget repo ${repo_url}, branch ${branch_name}... (${retries} attempts, ${delay}s delay)"
          for (( i=1; i<=retries; i++ )); do
            if git clone --depth 1 --branch "$branch_name" --single-branch "$repo_url" winget-repo; then
              echo "Successfully cloned branch '$branch_name'."
              break
            fi
            if [[ $i -lt $retries ]]; then
              echo "WARN: Clone attempt $i/$retries failed. Branch '$branch_name' might not exist yet. Waiting ${delay} seconds..."
              sleep $delay
            else
              echo "ERROR: Could not clone branch '$branch_name' from '$repo_url' after $retries attempts. Did GoReleaser job succeed and push the branch?"
              exit 1
            fi
          done

          cd winget-repo
          echo "Checking for manifest file '$manifest_path'..."
          if [[ -f "$manifest_path" ]]; then
              echo "Manifest file found!"
              cd ..
              exit 0
          else
              echo "ERROR: Branch '$branch_name' cloned, but manifest file '$manifest_path' not found within it."
              echo "Listing contents of ${APP_VERSION_NO_V} directory:"
              ls -l "manifests/s/${WINGET_PUBLISHER}/${WINGET_PACKAGE}/${APP_VERSION_NO_V}/" || true
              cd ..
              exit 1
          fi

      - name: Generate Locale Files from Templates
        env:
          # Use outputs from determine-release-info
          CURRENT_VERSION_NO_V: ${{ needs.determine-release-info.outputs.tag_name_no_v }}
          WINGET_PUBLISHER: ShipDigital
          WINGET_PACKAGE: PullWatch
        run: |
          #!/bin/bash
          set -eo pipefail
          echo "--- Generating locale files for ${CURRENT_VERSION_NO_V} from templates ---"
          locales=("de-DE" "es-ES" "fr-FR" "it-IT" "pt-BR" "pt-PT" "zh-CN")

          template_dir="main-repo/templates/winget/locales"
          target_base_dir="winget-repo/manifests/s/${WINGET_PUBLISHER}/${WINGET_PACKAGE}/${CURRENT_VERSION_NO_V}"
          source_manifest_version_file="${target_base_dir}/${WINGET_PUBLISHER}.${WINGET_PACKAGE}.installer.yaml"

          if [[ ! -d "$template_dir" ]]; then
            echo "ERROR: Template directory '$template_dir' not found."
            exit 1
          fi
          if [[ ! -f "$source_manifest_version_file" ]]; then
            echo "ERROR: Cannot read ManifestVersion. Source file '$source_manifest_version_file' not found (Wait step might have failed silently?)."
            exit 1
          fi

          TARGET_MANIFEST_VERSION=$(yq e '.ManifestVersion' "$source_manifest_version_file")
          if [[ -z "$TARGET_MANIFEST_VERSION" ]]; then
             echo "ERROR: Could not read ManifestVersion from '$source_manifest_version_file' using yq."
             exit 1
          fi
          echo "Target ManifestVersion read from installer: $TARGET_MANIFEST_VERSION"

          mkdir -p "${target_base_dir}"

          for locale in "${locales[@]}"; do
            source_file="${template_dir}/${WINGET_PUBLISHER}.${WINGET_PACKAGE}.locale.${locale}.yaml"
            target_file="${target_base_dir}/${WINGET_PUBLISHER}.${WINGET_PACKAGE}.locale.${locale}.yaml"

            if [[ -f "$source_file" ]]; then
              echo "Generating $target_file from template $source_file"
              cp "$source_file" "$target_file"
              schema_url="https://aka.ms/winget-manifest.locale.${TARGET_MANIFEST_VERSION}.schema.json"
              echo "Prepending schema header: $schema_url to $target_file"
              sed "1i\\# yaml-language-server: \$schema=${schema_url}" "$target_file" > tmp_locale && mv tmp_locale "$target_file"
              echo "Updating PackageVersion in $target_file to ${CURRENT_VERSION_NO_V}"
              yq e -i ".PackageVersion = \"${CURRENT_VERSION_NO_V}\"" "$target_file"
              echo "Updating ManifestVersion in $target_file to ${TARGET_MANIFEST_VERSION}"
              yq e -i ".ManifestVersion = \"${TARGET_MANIFEST_VERSION}\"" "$target_file"
            else
              echo "WARN: Source template file not found: $source_file"
            fi
          done
          echo "--- Locale file generation complete ---"

      - name: Enrich Winget Manifest (Installer)
        env:
          # Use outputs from determine-release-info
          APP_VERSION_NO_V: ${{ needs.determine-release-info.outputs.tag_name_no_v }}
          WINGET_PUBLISHER: ShipDigital
          WINGET_PACKAGE: PullWatch
          WINGET_MIN_OS: "10.0.0.0"
          WINGET_INSTALL_MODES_YAML: "['silent', 'silentWithProgress']"
          WINGET_UPGRADE_BEHAVIOR: "install"
          WINGET_COMMANDS_YAML: "['pull-watch']"
        run: |
          #!/bin/bash
          set -eo pipefail

          manifest_version="${APP_VERSION_NO_V}"
          manifest_dir="winget-repo/manifests/s/${WINGET_PUBLISHER}/${WINGET_PACKAGE}/${manifest_version}"
          manifest_file="${manifest_dir}/${WINGET_PUBLISHER}.${WINGET_PACKAGE}.installer.yaml"

          echo "--- Enriching Winget Installer Manifest ${manifest_file} for ${APP_VERSION_NO_V} ---"

          if [[ ! -f "$manifest_file" ]]; then
            echo "ERROR: Winget installer manifest not found at '$manifest_file'."
            echo "Listing contents of winget-repo/manifests/s/${WINGET_PUBLISHER}/${WINGET_PACKAGE}/${manifest_version}/:"
            ls -l "$manifest_dir" || echo "(Directory not found or empty)"
            exit 1
          fi

          echo "Found installer manifest: $manifest_file"
          yq e -i ".MinimumOSVersion = strenv(WINGET_MIN_OS)" "$manifest_file"
          yq e -i ".InstallModes = load(strenv(WINGET_INSTALL_MODES_YAML))" "$manifest_file"
          yq e -i ".UpgradeBehavior = strenv(WINGET_UPGRADE_BEHAVIOR)" "$manifest_file"
          yq e -i ".Commands = load(strenv(WINGET_COMMANDS_YAML))" "$manifest_file"

          echo "Installer manifest successfully enriched."
          echo "--- Updated Installer Manifest Content ---"
          cat "$manifest_file"
          echo "------------------------------"

      - name: Commit and Push Changes to Winget Fork
        env:
          # Use outputs from determine-release-info
          TAG_NAME: ${{ needs.determine-release-info.outputs.tag_name }}
          APP_VERSION_NO_V: ${{ needs.determine-release-info.outputs.tag_name_no_v }}
          WINGET_PUBLISHER: ShipDigital
          WINGET_PACKAGE: PullWatch
          WINGET_REPO_OWNER: ship-digital
          WINGET_REPO_NAME: winget-pkgs
          COMMIT_AUTHOR_NAME: "github-actions[bot]"
          COMMIT_AUTHOR_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          SIGNOFF_LINE: "Signed-off-by: Alessandro De Blasis <alex@deblasis.net>"
        run: |
          #!/bin/bash
          set -eo pipefail
          cd winget-repo

          git config --global user.name "${COMMIT_AUTHOR_NAME}"
          git config --global user.email "${COMMIT_AUTHOR_EMAIL}"

          readonly manifest_version_dir="manifests/s/${WINGET_PUBLISHER}/${WINGET_PACKAGE}/${APP_VERSION_NO_V}"

          if [[ ! -d "$manifest_version_dir" ]]; then
            echo "ERROR: Manifest directory '$manifest_version_dir' not found. Nothing to commit."
            cd .. && exit 1
          fi

          git add "$manifest_version_dir/"

          # Check if there are staged changes in the target directory
          if git diff --quiet --exit-code --cached -- "$manifest_version_dir/"; then
             echo "No changes detected in Winget manifests within '$manifest_version_dir' after enrichment/locale generation. Nothing to commit."
             cd .. && exit 0
          fi

          echo "Committing changes to Winget manifests in '$manifest_version_dir'..."
          COMMIT_MSG="ci(winget): update manifests for ${TAG_NAME}"
          git commit -m "$COMMIT_MSG" -m "$SIGNOFF_LINE"

          BRANCH_NAME="pull-watch-${TAG_NAME}"
          echo "Pushing manifest updates commit to branch ${BRANCH_NAME} in ${WINGET_REPO_OWNER}/${WINGET_REPO_NAME}..."
          # Use the GITHUB_TOKEN provided by the workflow runner for authentication
          # Ensure the token has permissions to write to the fork.
          git push https://${COMMIT_AUTHOR_NAME}:${{ secrets.GITHUB_TOKEN }}@github.com/${WINGET_REPO_OWNER}/${WINGET_REPO_NAME}.git HEAD:"${BRANCH_NAME}" --force-with-lease

          echo "Successfully pushed changes to winget fork branch ${BRANCH_NAME}."
          cd ..
